### ISSUE TITLE
Cannot get Logic Pro 8 to connect to PWM Logic software

### ISSUE THREAD

**Issue by kilomanjaro4** [joosthaverkort/PWMLogic#1]
Hello, 
I had need of a 4+ channel signal generator at low frequencies and as I was looking I saw this and I am super excited that this could work. I instantly downloaded the release package but can't get it to connect to my logic pro 8. Is there a method to do this? I have tried having the software open then connecting saleae, connecting saleae first then opening software, and opening Logic software to get device to have the green light turn on then close out of logic and open up your PWM software. I have also tried by leaving the logic software open. The PWN software always says Not connected      Not running. Do I need to install some older version of firmware? I bought my logic pro 8 in 2019.

**Comment by joostit** [comment]
Hi there,
I made this project like ten years ago and haven't maintained it for the last time in 2015. There's a good chance that the low-level drivers worked completely different back then than they do nowadays. This project is only online for reference purposes.

I'm afraid I cannot help you here, but feel free to take the code and try to get it to work yourself 😉
